export type FormData = {
  ingles: string
  espanol: string
  color: string
  subtitle1: string
  text1: string
  color1: string
  subtitle2: string
  text2: string
  color2: string
  subtitle3: string
  text3: string
  color3: string
  subtitle4: string
  text4: string
  color4: string
  subtitle5: string
  text5: string
  color5: string
  subtitle6: string
  text6: string
  color6: string
  subtitle7: string
  text7: string
  color7: string
  subtitle8: string
  text8: string
  color8: string
  subtitle9: string
  text9: string
  color9: string
}
