export const preguntas = [
  '¿Hay algún detalle que quieras conocer más a fondo?',
  '¿Puedo ofrecerte más información sobre esto?',
  '¿Tienes alguna otra duda relacionada con esto?',
  '¿Hay algún aspecto que quieras profundizar más?',
  '¿Te gustaría que te amplíe información sobre esto?',
  '¿Puedo aclarar algún otro punto sobre este tema?',
  '¿Tienes alguna otra pregunta que te gustaría hacer sobre esto?',
  '¿Hay algún detalle adicional que te gustaría conocer?',
  '¿Puedo asistirte con alguna otra consulta sobre esto?',
  '¿Hay algo más que te cause curiosidad sobre este tema?',
  '¿Tienes algún otro aspecto en mente que quieras explorar más?',
  '¿Hay algún otro asunto relacionado que te gustaría tratar?',
  '¿Te gustaría más información sobre algún detalle de esto?',
  '¿Puedo ayudarte con alguna otra pregunta sobre este tema?',
  '¿Hay algo más que te gustaría preguntar sobre esto?',
  '¿Te gustaría seguir hablando de algún aspecto de esto?',
  '¿Puedo proporcionarte más detalles sobre este punto?',
  '¿Hay algún aspecto adicional que quieras discutir?',
  '¿Tienes alguna otra duda relacionada con este tema?',
  '¿Puedo ayudarte con algún otro aspecto de esto?',
  '¿Te gustaría saber más sobre algún detalle de esto?',
  '¿Hay algún punto adicional que te gustaría revisar?',
  '¿Tienes alguna otra consulta que te gustaría hacer sobre esto?',
  '¿Puedo brindarte más información sobre este tema?',
  '¿Hay algún otro aspecto que quieras investigar más a fondo?',
  '¿Te gustaría seguir explorando algún punto de esto?',
  '¿Puedo ayudarte con alguna otra cuestión relacionada con esto?',
  '¿Hay algo más relacionado con este tema que te interese saber?',
  '¿Tienes alguna otra pregunta que quieras hacer sobre este asunto?',
  '¿Hay algún aspecto de esto que te gustaría abordar más?',
  '¿Te gustaría que aclare algún punto relacionado con esto?',
  '¿Hay algún aspecto adicional en el que pueda asistirte?',
  '¿Tienes alguna otra consulta relacionada con esto?',
  '¿Hay algún punto de esto que te gustaría entender mejor?',
  '¿Puedo ofrecerte más información sobre este detalle?',
  '¿Te gustaría seguir explorando este tema?',
  '¿Tienes alguna otra inquietud relacionada con esto que quieras resolver?',
  '¿Hay algún detalle adicional de esto que te gustaría conocer mejor?',
  '¿Puedo ayudarte con alguna otra cuestión sobre este tema?',
  '¿Te interesa saber algo más sobre este aspecto?',
  '¿Hay algún otro detalle sobre esto que te interese explorar?',
  '¿Puedo darte más información relacionada con este tema?',
  '¿Tienes alguna otra duda específica sobre esto?',
  '¿Hay algún punto que te gustaría analizar más en profundidad?',
  '¿Te gustaría conocer más sobre este aspecto en particular?',
  '¿Puedo ayudarte a aclarar algún otro punto de este tema?',
  '¿Tienes alguna otra pregunta que te gustaría formular sobre esto?',
  '¿Hay algún detalle que aún no esté claro y te gustaría saber más?',
  '¿Puedo asistirte con más información sobre este tema?',
  '¿Hay algo más sobre este asunto que te cause curiosidad?',
  '¿Tienes algún otro aspecto de esto en mente que quieras discutir?',
  '¿Hay algún otro punto relacionado con esto que te gustaría tratar?',
  '¿Te gustaría saber más sobre un aspecto específico de esto?',
  '¿Puedo ayudarte a resolver alguna otra duda sobre este tema?',
  '¿Hay algo más que te gustaría preguntar sobre este asunto?',
  '¿Te gustaría que continuemos hablando sobre algún punto de esto?',
  '¿Puedo proporcionarte más detalles sobre este tema?',
  '¿Hay algún aspecto adicional que quieras entender mejor?',
  '¿Tienes alguna otra duda en relación a esto que quieras aclarar?',
  '¿Puedo ayudarte con más información sobre este asunto?',
  '¿Te gustaría saber más sobre algún detalle específico de esto?',
  '¿Hay algún punto adicional que te gustaría conocer más a fondo?',
  '¿Tienes alguna otra consulta específica sobre este tema?',
  '¿Puedo brindarte más información que te ayude con esto?',
  '¿Hay algo más que te gustaría investigar dentro de este tema?',
  '¿Te gustaría seguir explorando algún aspecto de esto?',
  '¿Puedo ayudarte a profundizar en algún otro detalle relacionado?',
  '¿Hay algún aspecto relacionado que aún no hayamos cubierto?',
  '¿Tienes alguna otra pregunta específica sobre este tema?',
  '¿Hay algún aspecto de esto que te gustaría entender mejor?',
  '¿Te gustaría que aclare algún otro detalle relacionado con esto?',
  '¿Hay algún aspecto más en el que pueda asistirte?',
  '¿Tienes alguna otra consulta que quieras hacer sobre este tema?',
  '¿Hay algo más de esto que te gustaría discutir?',
  '¿Puedo ofrecerte más información sobre este punto?',
  '¿Te gustaría seguir profundizando en este tema?',
  '¿Tienes alguna otra inquietud relacionada con esto?',
  '¿Hay algún detalle adicional de este tema que te gustaría conocer?',
  '¿Puedo ayudarte a resolver alguna otra cuestión sobre este asunto?',
  '¿Te interesa saber algo más sobre este aspecto en particular?'
]
